name: Deploy to K3s

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Lowercase repo name and get SHA
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> ${GITHUB_ENV}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:latest
            ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }}

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to K3s
        run: |
          sed -i "s|DOCKER_IMAGE_PLACEHOLDER|ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }}|g" k8s/site.yaml
          kubectl apply -f k8s/site.yaml
          kubectl rollout restart deployment/personal-site